init: api for tasks
EskovDMTA/task_trello pull request #13
Opened 2022-12-11 16:13 UTC by EskovDMTA

2022-12-12 07:06 UTC, greybutton requested changes
приведи код в порядок, отступы пляшут, рубокоп проверь

2022-12-12 07:06 UTC, greybutton commented on app/models/task.rb
> +    event :test1 do
плохое именование, зачем 1?

2022-12-12 18:31 UTC, EskovDMTA commented on app/models/task.rb
> +    event :test1 do
Ошибка явная. При запуске тестов было предупреждение, что метод test уже определен в Object, тесты от этого не падали, но я решил поправить название и успешно про это забыл

2022-12-15 05:53 UTC, greybutton approved these changes

2022-12-15 11:17 UTC, merged